apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus/service-monitor.yaml
  - prometheus/config.yaml

configMapGenerator:
  - name: redis-service-dashboard
    files:
      - grafana/dashboards/redis-service-dashboard.json
    options:
      labels:
        grafana_dashboard: "true" 