apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  MONGODB_URI: "mongodb://root:example@mongodb:27017"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  REDIS_URL: "redis://redis:6379" 