apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    import { randomString } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

    export const options = {
        scenarios: {
            reservation_flow: {
                executor: 'ramping-vus',
                startVUs: 0,
                stages: [
                    { duration: '1m', target: 100 },
                    { duration: '2m', target: 100 },
                    { duration: '1m', target: 0 },
                ],
            },
        },
        thresholds: {
            http_req_duration: ['p(95)<500'],
            http_req_failed: ['rate<0.1'],
        },
    };

    const BASE_URL = 'http://ride-reservation-service:8000/api';
    const FACILITY_SERVICE_URL = 'http://facility-service:8000/api';
    let ACTIVE_FACILITIES = [];

    // ... (나머지 테스트 코드) 