apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-reservation-service
  template:
    metadata:
      labels:
        app: ride-reservation-service
    spec:
      containers:
      - name: ride-reservation-service
        image: kasd0134/msa-ridereservationservice:latest
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_SERVERS
          value: "kafka:9092"
        - name: REDIS_URL
          value: "redis://redis:6379"

        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ride-reservation-service
spec:
  selector:
    app: ride-reservation-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
