apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kasd0134/msa-external-services.git'  # Git 저장소 URL
    targetRevision: HEAD
    path: 'external-services/k8s'  # 매니페스트 경로
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
