apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo.git'  # Git 저장소 URL
    targetRevision: HEAD
    path: 'path/to/kubernetes/manifes ts'  # 매니페스트 경로
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true