apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mint-cocoa/msa_final.git'
    targetRevision: HEAD
    path: 'internal_services/k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
