apiVersion: argoproj.io/v2
kind: Application
metadata:
  name: theme-park-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mint-cocoa/msa_final.git'
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

