apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theme-park-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-repo.git'
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  sources:
  - repoURL: 'https://github.com/your-username/your-repo.git'
    targetRevision: HEAD
    path: 'k8s'
    helm:
      valueFiles:
      - values.yaml
  - repoURL: 'https://github.com/your-username/your-repo.git'
    targetRevision: HEAD
    path: 'internal_services/k8s'
    helm:
      valueFiles:
      - values.yaml

  

