version: '3.8'

services:
  ride_reservation_service:
    build: ./ride_reservation_service
    ports:
      - "8001:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

  notification_service:
    build: ./notification_service
    ports:
      - "8002:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

  real_time_tracking_service:
    build: ./real_time_tracking_service
    ports:
      - "8003:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
