version: '3.8'

services:
  ride_reservation_service:
    build: ./ride_reservation_service
    ports:
      - "8001:8000"
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis

  notification_service:
    build: ./notification_service
    ports:
      - "8002:8000"
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis

  real_time_tracking_service:
    build: ./real_time_tracking_service
    ports:
      - "8003:8000"
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka_service:
    build: ./kafca_service
    ports:
      - "8004:8000"
    environment:
      - KAFKA_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis
