version: '3.8'

services:
  ride_reservation_service:
    build: ./ride_reservation_service
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  notification_service:
    build: ./notification_service
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  real_time_tracking_service:
    build: ./real_time_tracking_service
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
