version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  user_service:
    build: ./user-service
    container_name: user_service
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/users?authSource=admin
      - DATABASE_NAME=users
    depends_on:
      - mongodb

  park_service:
    build: ./park_service
    container_name: park_service
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/parks?authSource=admin
      - DATABASE_NAME=parks
    depends_on:
      - mongodb

  facility_service:
    build: ./facility_service
    container_name: facility_service
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/facilities?authSource=admin
      - DATABASE_NAME=facilities
    depends_on:
      - mongodb

  ticket_service:
    build: ./ticket_service
    container_name: ticket_service
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/tickets?authSource=admin
      - DATABASE_NAME=tickets
    depends_on:
      - mongodb

volumes:
  mongodb_data:
